---
- name: Get palo alto device api key
  uri:
    url: "https://{{ inventory_hostname }}/api/?type=keygen&user={{ username }}&password={{ password }}"
    method: GET
    validate_certs: no
    body_format: json
    return_content: yes
  register: result


- name: Get palo alto device config
  uri:
    url: "https://{{ inventory_hostname }}/api/?type=export&category=configuration&key={{ result.content | regex_findall('^.*<key>(.*)<\\/key>') | first}}"
    method: GET
    validate_certs: no
    return_content: yes
  register: pa_config


- name: Parse the config in xml and save it in a readable output
  xml:
    xmlstring: " {{ pa_config.content }} "
    xpath: //config
    content: 'text'
    pretty_print: yes
  register: xml_output

- name: Save parsed config localy on the device
  local_action: copy content={{ xml_output.xmlstring }} dest=files/backups/{{ inventory_hostname }}.xml